// Recuperado do Sites, versão 2. Campos: dia, capítulo, referência, título, reflexão, oração.
export const days = [
  [
    1,
    1,
    "Daniel 1:1–21",
    "Uma decisão de fidelidade",
    "Daniel e seus amigos escolhem permanecer fiéis a Deus diante das exigências da corte.",
    "Peça firmeza para honrar a Deus nas decisões de hoje.",
  ],
  [
    2,
    2,
    "Daniel 2:1–23",
    "O sonho e a resposta de Deus",
    "Diante de um desafio impossível, Daniel reúne seus amigos para orar e recebe sabedoria.",
    "Apresente a Deus uma situação para a qual você precisa de direção.",
  ],
  [
    3,
    2,
    "Daniel 2:24–49",
    "A estátua e os reinos",
    "Daniel revela o sonho e reconhece que Deus governa sobre a história.",
    "Ore por confiança na soberania de Deus em tempos incertos.",
  ],
  [
    4,
    3,
    "Daniel 3:1–12",
    "A recusa diante da estátua",
    "Os amigos de Daniel se recusam a adorar a imagem erguida pelo rei.",
    "Peça coragem para manter suas convicções sob pressão.",
  ],
  [
    5,
    3,
    "Daniel 3:13–30",
    "A fornalha ardente",
    "Mesmo diante do fogo, os três amigos permanecem fiéis e experimentam livramento.",
    "Ore por confiança na presença de Deus nas provações.",
  ],
  [
    6,
    null,
    "Dia de meditação",
    "Releia e medite",
    "Volte aos versículos que mais falaram ao seu coração nesta semana.",
    "Ore sobre fidelidade e anote uma decisão prática.",
  ],
  [
    7,
    null,
    "Dia de meditação",
    "Pare e avalie",
    "Reserve um momento para avaliar sua caminhada de oração e jejum até aqui.",
    "Peça sabedoria divina para seguir os próximos dias.",
  ],
  [
    8,
    4,
    "Daniel 4:1–18",
    "O sonho da grande árvore",
    "Nabucodonosor relata seu sonho e busca sua interpretação.",
    "Peça um coração atento àquilo que Deus deseja mostrar.",
  ],
  [
    9,
    4,
    "Daniel 4:19–37",
    "Humilhação e restauração",
    "O rei é humilhado e, depois, reconhece a soberania do Altíssimo.",
    "Ore por humildade para reconhecer a dependência de Deus.",
  ],
  [
    10,
    5,
    "Daniel 5:1–12",
    "A escrita na parede",
    "Durante o banquete de Belsazar, surge uma mensagem que ninguém consegue explicar.",
    "Peça discernimento para não ignorar os sinais de Deus.",
  ],
  [
    11,
    5,
    "Daniel 5:13–31",
    "A queda da Babilônia",
    "Daniel interpreta a mensagem e o reino de Belsazar chega ao fim.",
    "Ore por reverência a Deus e responsabilidade nas suas escolhas.",
  ],
  [
    12,
    6,
    "Daniel 6:1–15",
    "A armadilha contra Daniel",
    "A fidelidade de Daniel na oração se torna alvo de uma conspiração.",
    "Peça perseverança para manter sua vida de oração.",
  ],
  [
    13,
    6,
    "Daniel 6:16–28",
    "Na cova dos leões",
    "Daniel é lançado na cova e Deus o preserva.",
    "Agradeça pela fidelidade de Deus e entregue seus medos a ele.",
  ],
  [
    14,
    null,
    "Dia de meditação",
    "Deus sobre reis e reinos",
    "Releia uma passagem dos capítulos 4 a 6 que marcou sua semana.",
    "Reflita e ore sobre a soberania de Deus.",
  ],
  [
    15,
    7,
    "Daniel 7:1–28",
    "Os quatro animais",
    "Daniel contempla uma visão de reinos e do domínio eterno de Deus.",
    "Peça esperança ao lembrar que o reino de Deus permanece.",
  ],
  [
    16,
    8,
    "Daniel 8:1–27",
    "O carneiro e o bode",
    "Uma visão complexa leva Daniel a buscar entendimento.",
    "Ore por paciência e humildade diante do que ainda não entende.",
  ],
  [
    17,
    9,
    "Daniel 9:1–19",
    "A oração de confissão",
    "Daniel se volta a Deus em oração, confessando os pecados do povo.",
    "Confesse com sinceridade e peça misericórdia.",
  ],
  [
    18,
    9,
    "Daniel 9:20–27",
    "As setenta semanas",
    "Daniel recebe uma resposta à sua oração e uma visão sobre o futuro.",
    "Peça confiança nos tempos de Deus.",
  ],
  [
    19,
    10,
    "Daniel 10:1–21",
    "A visão junto ao rio",
    "Daniel recebe uma visão e é fortalecido para ouvir.",
    "Ore por força e perseverança na oração.",
  ],
  [
    20,
    11,
    "Daniel 11:1–45",
    "Reis do Norte e do Sul",
    "Daniel ouve uma longa revelação sobre conflitos e poder.",
    "Ore por discernimento e firmeza em tempos de conflito.",
  ],
  [
    21,
    12,
    "Daniel 12:1–13",
    "A promessa final",
    "O livro termina com uma palavra de esperança e perseverança.",
    "Agradeça pelos 21 dias e peça fidelidade para continuar.",
  ],
];

export const weekNames = [
  "Fidelidade e sonhos",
  "Orgulho, queda e livramento",
  "Visões, profecias e resposta",
];
